




_select_data:
  aspect-ratio:
   -square
   -portrait
   -portrait-tall
   -landscape
   -landscape-wide

  column-sizes:
   col-6: One-Half
   col-12: Full-width
   col-4: One-Third
   col-3: One-Quater
   col-6_sm-12: One Half (Stacked)
   col-4_sm-12: One Third (Stacked)
   col-3_sm-12: One Quarter (Stacked)